name: fetch

on:
  schedule:
    - cron: '0 20 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: |
         pip install -r requirements.txt
         python sync.py
         git diff
         git config --local user.email "action@github.com"
         git config --local user.name "GitHub Action"
         git add data/*.csv
         git commit -m "Add files via upload" || exit 0
         git push 
